name: Folder Sync CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with PyLint
        run: find . -name '*.py' -exec pylint {} \;
          
      - name: Run tests with PyTest
        run: find main.py - exec pytest{} \;